{
  gROOT->SetStyle("Plain");
  gStyle->SetNdivisions(505);
  gStyle->SetNdivisions(505,"Y");
  gStyle->SetMarkerSize(1.2);
  //gROOT->LoadMacro("brick_utils.C");
  gSystem->Load("kkp/libkkp.so");
  //gROOT->LoadMacro("kkp_func.C");
  //gROOT->LoadMacro("~/macros/utils.C");
  gROOT->Macro("plot_kkp_bm_sub.C");
}
