void style() {
  gStyle->SetOptStat(0);
  gStyle->SetLineWidth(2);
  gStyle->SetFrameLineWidth(2);
  gStyle->SetNdivisions(505);
  gStyle->SetNdivisions(505,"Y");
  gStyle->SetPadRightMargin(0.05);
  gStyle->SetPadTopMargin(0.05);
  gStyle->SetPadLeftMargin(0.12);
  gStyle->SetOptTitle(0);
  gStyle->SetTitleFont(42);
  gStyle->SetTitleSize(0.05);
  gStyle->SetTitleSize(0.05,"Y");
  gStyle->SetLabelSize(0.04);
  gStyle->SetLabelSize(0.04,"Y");
  gStyle->SetTitleOffset(0.9);
  gStyle->SetMarkerSize(1.5);
  gStyle->SetTextFont(42);
  gStyle->SetPadTickX(1);
  gStyle->SetPadTickY(1);
}
