Universe   = vanilla
Executable = condorJetClusteringCorrections
JobID = $(Process)
Arguments  = "20000000 $INT(ClusterId)_$INT(JobID) 1 $INT(ClusterId)"
Log        = ../JetClusteringCorrections/$INT(ClusterId)_$INT(JobID).log
Output     = ../JetClusteringCorrections/$INT(ClusterId)_$INT(JobID).out
Error      = ../JetClusteringCorrections/$INT(ClusterId)_$INT(JobID).error
+JobCategory = "long"
+SingularityImage = "/user/templon/ALICEnikhef.sif"
queue 50
